name: Generate & Commit Static HTML

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-static:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (for push)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Build docker image
        run: docker build -t php-static:latest .

      - name: Run container to generate static HTML
        # mount workspace so generated files are written back to the repo
        env:
          # you can override EXCLUDE_REGEX here if you want different exclude rules
          EXCLUDE_REGEX: 'admin|test|wp-admin|private|/tmp/'
        run: docker run --rm -v "${{ github.workspace }}:/app" -e EXCLUDE_REGEX="${{ env.EXCLUDE_REGEX }}" php-static:latest

      - name: Commit & push static_html_directory (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add static_html_directory
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update static HTML snapshot (generated by workflow)"
            git push origin HEAD:main
          fi
